### ISSUE TITLE
sorting addresses in the constructor

### ISSUE THREAD

**Issue by miktam** [SylTi/solidity-smart-contracts#1]
https://github.com/SylTi/solidity-smart-contracts/blob/69ba7acbd52de4cc4c1fc294105633cee556915c/contracts/MultiSig.sol#L33

could you sort just inside the constructor? so order in the list could be arbitrary

**Comment by SylTi** [comment]
Hey! Thanks for checking this out.

You actually need to do the check inside the payment loop `require(currentAddress > previousOwner, "invalid order of signature");`, this is done to check that each signature is unique, otherwise, a single participant in the multiSig scheme could use is own signature multiple times and reach the threshold that way.
